spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  flyway:
    enabled: true
  cloud:
    gcp:
      pubsub:
        project-id: ${GCP_PROJECT_ID:lloyds-offers}

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
